/*
 * Nuki web3 home-service
 *
 * ...
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type OpenDoorResponse struct {

	Status *interface{} `json:"status,omitempty"`
}

// AssertOpenDoorResponseRequired checks if the required fields are not zero-ed
func AssertOpenDoorResponseRequired(obj OpenDoorResponse) error {
	return nil
}

// AssertRecurseOpenDoorResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of OpenDoorResponse (e.g. [][]OpenDoorResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseOpenDoorResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aOpenDoorResponse, ok := obj.(OpenDoorResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertOpenDoorResponseRequired(aOpenDoorResponse)
	})
}
